### ISSUE TITLE
Better hot key choice / different system for skills?

### ISSUE THREAD

**Issue by Cervator** [Terasology/EventualSkills#5]
@Josharias I changed the 'K' to "L' on opening the skills window to avoid the conflict with Tasks and wanted to let you know.

Rather than continue our sprawl into extended hot key land I wonder if we could do something differently. You've got the more complete system where it could fit in.

A character screen

I've kept 'C' reserved more or less for that where it would be sitting well and be very handy for a player. Could keep more than just skills in there. Probably could even do a tabbing system where you might have skills, inventory, gear, achievements, creatures, friends list, etc. When we need that amount of space anyway, to begin with lots will probably fit on one screen.

I realize that's a big challenge but sort of suspect you're slowly drifting in that direction already, aware or not ... :-)

**Comment by msteiger** [comment]
I wanted to use `Q` for the quest system, but that key was already bound to "throw item". So I just went with the next free key I could think of. 

Long story short: we could use a different key for quests as well.

**Comment by Cervator** [comment]
Yup, I went hunting earlier, 'k' was the only free option in "tasks" although maybe 'u' is available for "quests" - were we going to do the rename or is there enough stuff to have both a task system and a quest system?

In any case we need to curtail hot key growth in favor of some better option eventually, lest we run out of keys :-)

**Comment by jdrueckert** [comment]
I believe in many games `J` is used for quests (often as part of some kind of Journal).
Maybe we should think about some tabbed UI element, in the sense of: If `Quests` only is active and you hit `J`, the quest window opens. If additionally `Journal` is active and you hit `J` you'll get a window with two tabs, an inactive one for quests and an active one for the journal.

`MasterOfOreons` task selection screen has some kind of tabs. Not sure about the feasibility of the combination of screens of different modules, though.

**Comment by jdrueckert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cross-Module UI Screen](https://trello.com/c/hej4yNbR/93-cross-module-ui-screen)

**Comment by jdrueckert** [comment]
Moving the discussion outside of this module in a [trello card](https://trello.com/c/hej4yNbR/93-cross-module-ui-screen) as IMO it shouldn't be discussed in the scope of a single module but on a broader scope. Also asked for architectural in https://discord.com/channels/270264625419911192/577194115725262912/970253569343230032
